targets:
  $default:
    builders:
      copyable|copyable:
        generate_for:
          include:
            - lib/**.dart

builders:
  copyable:
    import: "package:copyable_plus/src/copyable_generator.dart"
    builder_factories: ["copyableGenerator"]
    build_extensions: {".dart": [".copyable.dart"]}
    auto_apply: dependents
    build_to: source
