name: copyable
description: >-
  A Dart annotation and code generator that creates `copyWith`, `toJson`, and `fromJson`
  methods for your immutable classes.
version: 1.0.0
repository: https://github.com/itschillipill/copyable
homepage: https://github.com/itschillipill/copyable

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^7.4.4
  build: ^2.4.2
  meta: ^1.10.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.24.0
  json_serializable: ^6.7.1
